name: Build and Publish

on:
  push:
    branches:
      - master  # имя основной ветки

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy dist folder to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: dist/*
          target: /home/siter/web/ano-otvet.ru/public_shtml/

      - name: Restart Remote Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username:  ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            systemctl restart nginx
